name: Storage
summary: This is a deployment of an Azure Storage Account from AVM using Bicep.
description: Deploys a storage account from Azure Verified Modules (AVM) using Bicep.
templatePath: main.bicep
runner: Bicep
parameters:
- id: "location"
  name: "Location"
  description: "The location for the Storage Account"
  type: "string"
  default: "westeurope"
  required: true
- id: "storageAccountName"
  name: "Storage Account Name"
  description: "The name of the Storage Account"
  type: "string"
  default: ""
  required: true